Makefile
Especially for benchmarking against tip (or testing generics), it's
helpful to be able to specify a different Go compiler. This commit lets
the user (optionally) specify the toolchain they'd like to use with the
$GO environment variable.
Since `go fmt` doesn't support all the flags we need, this change
requires building `cmd/gofmt` in `bin/` and using that binary.
=> Support overriding Go compiler from environment

client.go, connect.go, handler.go, interceptor_ext_test.go, nop_stream.go, protobuf_util.go, protocol.go, protocol_grpc.go, protocol_grpc_client_stream.go, protocol_grpc_handler_stream.go
=> Rename Specification -> Spec

.github/CONTRIBUTING.md
Add CLA link. The connect-go CLA link works.
=> Update CONTRIBUTING.md to include CLA

README.md, cmd/protoc-gen-connect-go/main.go, connect.go, go.mod, go.sum, internal/gen/connect/ping/v1/pingv1connect/ping.connect.go
Update README and constants for release.
=> Prep for v0.1.0

.github/PULL_REQUEST_TEMPLATE/pull_request_template.md
We can edit the text, but just putting something basic down.
=> Add basic pull request template

connect_ext_test.go, interceptor_ext_test.go
Add test cases to verify the behavior of the WithCompressMinBytes
handler option.
=> add tests for WithCompressMinBytes

.github/workflows/ci.yaml
=> Update to Go 1.19 RC2

connect.go
=> Back to development

connect.go
=> Prepare for v0.3.0

connect.go
Prepare for the next release, and fix #424.
=> Prepare for v1.4.1

connect.go
@mattrobenolt has made a bunch of nice performance improvements. Let's
cut a release so he can use them :)
=> Prepare for v1.5.1

option.go
Copy edits to the WithConditionalHandlerOptions GoDoc.
=> Improve WithConditionalHandlerOptions docs

.github/CONTRIBUTING.md
**Before submitting your PR:** Please read through the contribution guide at https://connectrpc.com/connect/blob/main/.github/CONTRIBUTING.md
=> Drop Buf reference in contributing guide

Makefile
Forgot one occurrence in the previous PR.
=> Remove lingering $BIN

Makefile
Update to v1.26.1 of the Buf CLI.
=> Update Buf CLI

connect.go
Bump the version constant in preparation for v1.11.1.
=> Prepare for v1.11.1

.github/workflows/ci.yaml, .github/workflows/windows.yaml
=> Drop actions cache

LICENSE
Missed updating the LICENSE file in PR https://github.com/connectrpc/connect-go/pull/667
=> Fix LICENSE file years

connect.go
Below are the draft notes for the release:
----
* Add `package_suffix` option to `protoc-gen-connect-go` to allow specifying the output directory of generated code by @bufdev and @emcfarlane in https://github.com/connectrpc/connect-go/pull/803
* Change stream client closures to be non-blocking by @emcfarlane in https://github.com/connectrpc/connect-go/pull/791
* Fix comment typo spelling of optimize by @yoshihiro-shu in https://github.com/connectrpc/connect-go/pull/786
* Remove reader allocation for compressors pools by @emcfarlane in https://github.com/connectrpc/connect-go/pull/792
* @yoshihiro-shu made their first contribution in https://github.com/connectrpc/connect-go/pull/786
**Full Changelog**: https://github.com/connectrpc/connect-go/compare/v1.17.0...v1.18.0
=> Prepare for v1.18.0

connect.go
Below are the draft notes for the release, this is a patch release to fix the protoc-gen-connect-go issue:
----
* Fix protoc-gen-connect-go schema variable case handling by @emcfarlane in https://github.com/connectrpc/connect-go/pull/808
**Full Changelog**: https://github.com/connectrpc/connect-go/compare/v1.18.0...v1.18.1
=> Prepare for v1.18.1

recover.go
For some reason, this passed an empty spec and nil headers for streaming RPCs, though the Go docs don't suggest anything of the sort.
Also, as of Go 1.21 (which this module now requires), a call to `recover()` will never return nil if a panic occurred; if the panic value was `nil`, a *[`runtime.PanicNilError`](https://pkg.go.dev/runtime@master#PanicNilError) will be recovered instead. So I simplified the panic-handling to do the simple, idiomatic recovery, since it is now adequate.
=> Include valid spec and headers when calling recover handler for streaming RPCs

connect.go
Below are draft notes for this release. 
This release introduces the highly requested "simple" flag for code generation, making Connect significantly more ergonomic for everyday RPC development.
The new simple flag in protoc-gen-connect-go generates cleaner, more intuitive client and handler interfaces that eliminate request/response wrappers for most use cases. This addresses community feedback about verbosity and provides a more straightforward API. When enabled, metadata (headers/trailers) can be passed through context instead of explicit wrapper objects, optimizing for the common case where developers don't need direct access to HTTP headers.
* Add simple flag for more ergonomic generated code by @bufdev and @smaye81 in https://github.com/connectrpc/connect-go/pull/851
* Update Go to …
=> Prepare for v1.19.0
