- internal/assert/assert_test.go
I took a peek at `assert` and added a few more test cases.
`Value.IsNil()`'s documentation only mentions pointers but the implementation handles `reflect.UnsafePointer` too. I don't know if it's important enough to warrant a change in `Nil`/`NotNil` tho.
> Add more assert.Nil/NotNil tests

- README.md
I was playing around with a poorly configured client and was hitting an
endpoint for another package. The default response returned by
http.NotFound doesn't work well with gRPC/Twirp clients. I think it's
prudent to include the fallback in the example and let expert users
remove it in case they want to do things differently.
If this is a good idea, we should update the docs to match.
> Add bad route fallback in README.md

- header.go
- header_test.go
Expand IsReservedHeader to include the following reserved header keys:
* The empty key -- per RFC 7230, Section 3.2
* Keys starting with ":" -- per RFC 7540, Section 8.1.2.1
* Keys with characters outside of this this alphabet: a-z, 0-9, "-", "_",
and "." -- per gRPC spec, Header-Name rule
NB: Since reRPC treats header keys as case insensitive and changes their
casing based on the transport, we extend the gRPC Header-Name rule to
include A-Z.
Fixes the keys part of #8
> Expand IsReservedHeader checks

- bad_route.go
- header.go
- header_test.go
- interceptor_example_test.go
- metadata.go
- metadata_test.go
- rerpc_test.go
- stream.go
Remove `ImmutableHeader` and make all headers mutable. This lets
interceptors change the visibility of headers for code deeper in the
chain, which is particularly useful for authn/authz-related stuff. As a
nice side benefit, we remove another exported type.
Fixes #18.
> Make all headers mutable

- bad_route.go
- cmd/protoc-gen-go-rerpc/rerpc.go
- interceptor.go
- interceptor_example_test.go
- interceptor_test.go
- internal/crosstest/v1test/cross_rerpc.pb.go
- internal/health/v1/health_rerpc.pb.go
- internal/ping/v1test/ping_rerpc.pb.go
- rerpc_test.go
- short_circuit_test.go
- stream.go
Change the core interfaces (Stream and Func) to take the empty interface
instead of proto.Message. This opens up space to support other encodings
(e.g., flatbuffers, Thrift, msgpack) later on.
As a side benefit, it makes using Go 1.18 generics much more ergonomic.
(We may or may not actually do that.)
> Reduce protobuf coupling

- connect_ext_test.go
- protocol_grpc_handler_stream.go
- protocol_grpc_util.go
> Use CodeInternal when user-supplied Codecs can't marshal Status

- connect_ext_test.go
- protocol_grpc_client_stream.go
If a client mistakenly connects to an HTTP/1.x server and tries to start
a bidi stream, fail early with an explicit error message rather than
returning a cryptic, low-level error later on.
This came up most recently when @robbertvanginkel was using Connect, but
he wasn't the first.
> Improve error when clients try bidi over HTTP/1.x

- Makefile
- go.mod
- go.sum
`make lintfix` depends on `golangci-lint`. Also updates `xerrors` to the
latest version.
> Fix Make dependency

- bench_test.go
- client.go
- client_example_test.go
- client_stream.go
- cmd/protoc-gen-connect-go/main.go
- connect_ext_test.go
- interceptor_example_test.go
- interceptor_ext_test.go
- internal/gen/connect/connect/ping/v1/pingv1connect/ping.connect.go
Per discussion. While returning an error from `NewClient` does make a lot of sense to do some preflight validation, it's painful to use in a lot of cases, and we can just effectively do the validation before the first call. All errors that come up in practice are things you find within seconds of using the `Client` for the first time, and you fix once, and never hit again. On balance, this seems like a good tradeoff.
I am not in love with the propagation of the `err` field.
> Do not return error from Client constructor

- .github/CONTRIBUTING.md
We were still using bufbuild/connect - this changes it to bufbuild/connect-go.
Just in case it went under: There's also a TODO for the CLA.
> Update names in CONTRIBUTING.md

- compression.go
- envelope.go
- protocol_grpc.go
- protocol_grpc_client_stream.go
- protocol_grpc_handler_stream.go
- protocol_grpc_handler_stream_test.go
- protocol_grpc_lpm.go
So that we can share code between our implementations of the Connect and
gRPC protocols, factor enveloping (aka length-prefixed messages) and
compression out of the gRPC-specific code.
> Factor enveloping and compression out of gRPC

- connect_ext_test.go
- handler.go
- header.go
- protocol.go
- protocol_grpc.go
- protocol_grpc_util.go
Now that we've defined the Connect protocol, we can simplify the protocol
interfaces: content-type negotiation is simpler, so the interface gets smaller.
This is also an easy moment to fix a bug in server-side timeout handling.
> Fix server-side timeout handling

- protocol_grpc_client_stream.go
This returns a more intuitive `Unavailable` error when issuing a request to an unreachable host.
> Return an Unavailable error on failed requests

- protocol_connect.go
Unmarshalers embed `envelopeReader`, so we can use shorter-form field
access.
> Leverage embedding more

- code.go
- envelope.go
- error.go
- error_test.go
- protocol_connect.go
- protocol_grpc.go
As @mfridman and @smaye81 use Connect more and more, they're feeling the
lack of this function. It's a very small API, but a noticeable quality
of life improvement when working with custom error types.
Fixes TCN-86
> Export AsError

- bench_test.go
- client.go
- connect_ext_test.go
- handler.go
- option.go
Now that we're applying the default handler and client configuration in
the main connect package (vs passing options from the generated code),
we don't need to export `WithGzip` or `WithProtoBinaryCodec`.
After a lot of discussion, we've also decided to rename the compression
options. I've kept `WithCompression`, but made it a `HandlerOption`. For
clients, we now have `WithAcceptCompression` and `WithSendCompression`.
Since handlers accept JSON by default, I've made `WithProtoJSONCodec` a
`ClientOption` and shortened it slightly to `WithProtoJSON`. (We don't
do `WithGRPCProtocol` or `WithSendGzipCompression`, so this seems more
consistent too.)
Overall, this reduces the number of exported options and IMO makes the
naming more straightforward.
Fixes TCN-65
> Rename compression options, unexport defaults

- client.go
- client_stream.go
- cmd/protoc-gen-connect-go/main.go
- connect_ext_test.go
- internal/gen/connect/connect/ping/v1/pingv1connect/ping.connect.go
Rather than `ServerStreamForClient`, change to `ClientServerStream`
(with similar changes for server and bidi streaming).
I'm unsure about this - it's not clear to me that we're making things
better. The names are definitely shorter, but I think we may be losing a
little clarity? (Frankly, I'm also a little embarrassed to ship
`ClientClientStream`.)
Fixes TCN-65
> Rename client stream types

- connect_ext_test.go
- duplex_http_call.go
seems like there is a regression around the recent `CodeUnavailable` changes
> fix context error got wrapped by CodeUnavailable

- client.go
- client_stream.go
- cmd/protoc-gen-connect-go/main.go
- connect_ext_test.go
- internal/gen/connect/connect/ping/v1/pingv1connect/ping.connect.go
The change to client stream names is overall worse. The docs are worse, the
names are more confusing in context, and `ClientClientStream` is a particular
wart. Revert!
This reverts commit e4f4f5438e7a9c4c4b030384f4062534a1122c3c.
> Revert change in client stream names

- protocol_connect.go
Ooops! I used a content-type from an old draft.
> Use streaming Content-Type from protocol

- cmd/protoc-gen-connect-go/main.go
- connect_ext_test.go
- handler.go
- handler_stream.go
- internal/gen/connect/connect/ping/v1/pingv1connect/ping.connect.go
Rather than having handlers implementing client streaming methods call a
method to send the response, make things more like unary: they should
just return `(response, error)`.
> Improve client streaming ergonomics

- duplex_http_call.go
- error.go
This is pretty hacky, but it works. A few notes:
- Adding a test for this is a little difficult I think since it requires grpc-go to be reproduced, but we can talk about it.
- We will need to update the docs link.
- I prefixed the error instead of suffixed so I could use `%w`, let me know your thoughts.
> Special-case errors where h2c is not configured and where connect.WithGRPC is not used

- .golangci.yml
- LICENSE
- README.md
- client_example_test.go
- client_stream.go
- cmd/protoc-gen-connect-go/main.go
- code.go
- codec.go
- connect.go
- error.go
- handler_example_test.go
- header.go
- interceptor.go
- interceptor_example_test.go
- option.go
- protocol_connect.go
- protocol_grpc.go
- Disable automatic client compression where appropriate
- Add GoDoc for binary header splitting
- Update Error GoDoc for metadata
- Revert "Mark repository as a work in progress"
- Reword README to match connect.build
- Simplify examples
- Polish GoDoc a bit more
> Docs & README

- .github/release.yml
It's hard to test, but I _think_ that this config will get us reasonable
release notes without any manual work.
https://github.blog/2021-10-04-beta-github-releases-improving-release-experience/
https://docs.github.com/en/repositories/releasing-projects-on-github/automatically-generated-release-notes
> Add automated release notes config

- option.go
I felt that the diagram demonstrating the flow of information across
server interceptors, the network, and client interceptors could be more
readable.
This makes the following changes to it:
- Use ":" as a vertical ellipsis for "A B ... Y Z"
- Turn the network entries into a single delimited layer that the
requests pass through
- Curve the lines at edges with `'` instead of `|` and `-`
- Increase distance between left and right sides by two more spaces
- Add arrow end/start around "handler logic"
> WithInterceptors: Improve ASCII diagram

- README.md
The license link in the README points to:
https://github.com/bufbuild/connect-go/blob/main/LICENSE.txt
With an error:
> The 'bufbuild/connect-go' repository doesn't contain the 'LICENSE.txt' path in 'main'.
This PR fixes the link.
> readme: fix license link

- connect.go
- handler.go
We're currently using two generic functions to unmarshal unary requests
from Receivers. Because the two functions must use structs as their type
parameters (and structs have different gcshapes), we're stenciling a new
version of each function for each unary RPC.
These functions aren't complex enough to warrant this binary bloat. It's
simple enough to inline the logic where we use it instead.
(I don't think we need to be paranoid about this category of problems,
though - the Go generics implementation will almost certainly get better
over the next few releases, so it's not worth contorting our code to
work around imperfections in 1.18.)
> Stencil fewer functions

- .github/ISSUE_TEMPLATE/anything_else.md
When you go to create a new issue, it effectively has an "anything else" link built in.
> Delete "Anything Else" issue template

- handler.go
gRPC-Go has decided to care about normal HTTP semantics and changed this
behavior in a [minor release](https://github.com/grpc/grpc-go/releases/tag/v1.47.0). We can delete our explanatory comment now.
> Remove comment after "behavior change" in grpc-go

- client_stream.go
- client_stream_test.go
If a client fails initialization, it is expected that all calls on the
underlying streams short circuit and return the initialization error.
Additionally, calls to any other methods (i.e. RequestHeader) should
work without a panic.
Update ClientStreamForClient, ServerStreamForClient, and
BidiStreamForClient to be safe from panics when created with an
initialization error.
> guard against panics in client_stream

- code.go
- code_test.go
The minCode constant should be set to CodeCanceled, not CodeUnknown. Add
test coverage to ensure that known codes don't unmarshal when using
"code_<num>" encoding.
> fix minCode constant

- duplex_http_call.go
Update duplex_http_call to handle a nil response in the Read() and
ResponseStatusCode methods for consistency with other methods. Change
the signature of `ResponseStatusCode` to return an error if the returned
response is nil.
> ensure consistent nil response handling

- protocol_connect.go
Yikes! [Per the specification](https://connect.build/docs/protocol#streaming-request), we should be using `Connect-Content-Encoding` here.
Fixes TCN-151.
> Fix Connect header constant

- connect.go
- handler.go
- handler_ext_test.go
- handler_test.go
- protocol.go
Add some tests to verify the HTTP 405/415 errors. Refactor the code to
simplify readability. Fix a documentation typo and use consistent
receiver names in connect.go.
> improve test coverage in handler

- connect_ext_test.go
- duplex_http_call.go
- handler_ext_test.go
Create a test which adds support for 'deflate' compression using the
stdlib. Expand test coverage in handler_ext_test to add a test for
unsupported content encoding. Consistently call
`d.BlockUntilResponseReady()` in all places in duplex_http_call.
> add test for custom handler/client compression

- connect_ext_test.go
Update connect_ext_test to add tests to verify error handling with
invalid timeouts.
> add tests for connect timeout handling

- client_ext_test.go
Add tests which cover the case where `connect.NewClient` fails during
initialization. In this case, the initial error is saved and any
operations on the client fail fast with the initial error.
> add tests for client init failures

- connect_ext_test.go
There is an existing test for unary calls - add a similar test to verify
streaming calls.
> add timeout test to streaming client call

- option.go
`ioutil.Discard` was deprecated in Golang 1.16.
> Replace ioutil.Discard with io.Discard

- cmd/protoc-gen-connect-go/main.go
Fixes https://github.com/bufbuild/connect-go/issues/297.
`protoc` and `buf` both expect `CodeGeneratorResponses` to have unix-style paths https://github.com/protocolbuffers/protobuf/blob/main/src/google/protobuf/compiler/plugin.proto#L124=
> Always use unix-style paths for CodeGeneratorResponses

- connect_ext_test.go
Instead of using time.Sleep with small increments, instead create a
context using `WithDeadline(...)` with an expired time.
> attempt to fix flaky timeout tests

- connect_ext_test.go
- protocol_connect.go
- protocol_grpc.go
Currently, we're assuming that gRPC responses without a Grpc-Status trailer
are successes. This case doesn't come up in practice, but the specification
requires this trailer (the message and base64-encoded status proto are
optional).
Fixes #279.
> Require grpc-status trailer with gRPC protocol

- protocol_grpc.go
Update to cache the underlying error, not the connect.Error (as this is
mutated with updates to meta).
> fix race condition caught by unit tests

- compression.go
- compression_test.go
After #269, it was possible to generate an Accept-Encoding header with
duplicate values.
This is purely aesthetic, but an intentional side effect. This happens
if you're trying to override a previously defined one.
When the values were purely in map, they naturally deduped because they
keys overwrote previous values.
This adds tests to cover this compressionPool for the strict ordering of
names, as well as removing duplicate values.
I added a very light generic orderedSet[T comparable] to this, since I
think there are other places this can be leveraged. It's just a nice
tool to have. I can remove this if you'd prefer.
> Dedupe compression algorithm names

- compression.go
- protocol_connect.go
Update comparison to work properly on 32-bit architectures.
Addresses an issue introduced in #311.
> fix issues on 32-bit platforms

- compression.go
- envelope.go
- protocol_connect.go
Remove duplicate casts in compression pool's Decompress function by
ensuring the maxReadBytes parameter is an int64. This requires fewer
casts in the implementation to avoid potential issues.
> improve decompress signature

- option.go
- recover.go
- recover_ext_test.go
It's super-common for servers to want to recover from panics and control
the error message that clients see. This PR adds a HandlerOption to
recover from panics.
This is nice to have in connect proper for two reasons:
* Recovering properly is more nuanced than the usual
`if r := recover(); r != nil`.
* It's a good way to exercise the interceptor API.
FYI @kohenkatz
> Add an option for panic-recovering interceptor

- duplex_http_call.go
- error.go
- recover_ext_test.go
HTTP/2 includes its own set of error codes, which are sent in RST_STREAM
frames. When servers send one of these codes to clients, we should map
the HTTP/2 code back to one of our status codes.
> Map HTTP/2 RST_STREAM codes back to RPC codes

- README.md
Add links to Studio and connect-web to the ecosystem section of the
README.
> Add Studio and connect-web to README

- client_stream.go
- client_stream_test.go
- handler_stream.go
- handler_stream_test.go
Currently, iterator-style streams re-use the same memory for each
received message. This is a satisfying little efficiency, but it's very
likely to cause confusion among users - they'll retain a reference to a
message, call `Receive()` again, and wonder why the retained reference
has changed out from under them. We should anticipate this confusion and
allocate for each `Receive`. As a nice side effect, this makes
`vtprotobuf` Codecs behave properly by default - no need to explicitly
reset messages.
This PR also adds a `Conn()` method to each stream that exposes the
underlying connection. This lets users who want a different high-level
stream API write their own wrapper types: perhaps they'd like to avoid
allocations more aggressively, or they want every stream constructor to
also require …
> In iterators, allocate new msg for each Receive

- README.md
We don't need to special-case Go 1.18 support, since all of the Go
team's supported versions now include generics.
> Shorten stability section of README

- compression.go
- connect_ext_test.go
- envelope.go
- protocol_connect.go
Per https://github.com/grpc/grpc/blob/master/doc/statuscodes.md, we should be
using CodeResourceExhausted here. My fault for not catching this in code
review.
> Fix error code for ReadMaxBytes

- connect_ext_test.go
- envelope.go
- maxbytes.go
- maxbytes_go118.go
- option.go
- protocol_connect.go
The `ReadMaxBytes` option is nice, but we should also return
properly-coded errors when `net/http.MaxBytesHandler` middleware is in
play. This has no API surface area, but it's a nice improvement.
> Add support for http.MaxBytesHandler

- client.go
- client_ext_test.go
- client_stream.go
- connect.go
- connect_ext_test.go
- handler.go
- handler_stream.go
- protocol.go
- protocol_connect.go
- protocol_grpc.go
On requests and streams, expose the peer's address. For clients, the address is the host or host:port, parsed from the URL. For servers, the address is an IP:port pair, provided by `net/http` as `Request.RemoteAddr`.
In https://github.com/bufbuild/connect-go/issues/357, a handful of users asked for this information for logging, per-IP rate limiting, and a variety of other server-side concerns. It's also necessary for OpenTelemetry interceptors (https://github.com/bufbuild/connect-go/issues/344).
Fixes https://github.com/bufbuild/connect-go/issues/357.
> Expose peer information to handlers and clients

- .golangci.yml
- Makefile
- README.md
- connect.go
- go.mod
- go.sum
- handler.go
We've done enough with OpenTelemetry and client-side load-balancing to be
comfortable, so there's little benefit to holding off. Let's commit to a stable
release!
> Prepare for v1.0

- connect_ext_test.go
- error.go
`connect-go` doesn't typically shorten "error" to "err" in exported
APIs. (For example, we have `ErrorWriter` instead of `ErrWriter`.)
Rename `IsWireErr` to match, and add some more GoDoc to motivate usage.
> Rename IsWireErr -> IsWireError

- .github/workflows/windows.yaml
See https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
> Update Github Actions outputs to new format

- client_ext_test.go
- connect.go
- connect_ext_test.go
- protocol.go
- protocol_connect.go
- protocol_grpc.go
Currently, observability interceptors must parse the `Content-Type`
header to determine which RPC protocol is in use. This isn't awful, but
it's so easy for `connect-go` to expose directly that we might as well.
I chose to use our own strings rather than repurposing OpenTelemetry's
semantic conventions here. The OTel strings are less nice in this
context, and the packages are all unstable and subject to change.
@joshcarp, LMK if this seems like a bad tradeoff to you.
> Add RPC protocol to Peer

- client_ext_test.go
- compression_test.go
- connect_ext_test.go
- error_test.go
- interceptor_ext_test.go
Adds misc tests, almost to 90%
> Bump test coverage to 90%

- client_ext_test.go
- connect_ext_test.go
- protocol_connect.go
- Maps a zero code of `connectWireError` to a CodeUnknown in `connectWireError) asError() *Error `
This could have been done in the unmarshaling to `connectWireError` but I chose to leave that to be exactly what was read off the wire. 
- Adds nil guard in `validateResponse` for asError
- Adds tests for error mapping
Fixes: https://github.com/bufbuild/connect-go/issues/396
> Fix panic on zero send from server

- .golangci.yml
`golangci-lint` includes `gci` by default, so we can disable `goimports`. The auto-fix function still works, so `make lintfix` is enough to reformat any files with incorrectly grouped imports.
> Format imports with GCI

- connect_ext_test.go
- protocol.go
- protocol_connect.go
- protocol_grpc.go
The `http.Flusher` interface isn't part of the `http.ResponseWriter`
interface, but it's implemented by the HTTP/1 and HTTP/2 writers
provided by the standard library. It's also critical to Connect:
streaming handlers must flush messages to ensure that the client
receives them. This PR adds a check for unflushable response writers;
when the response writer for a streaming procedure can't be flushed, we
now return an explicit error instead of hanging.
Fixes #393.
> Ensure streaming ResponseWriters implement Flush

- connect_ext_test.go
- handler.go
If an HTTP/1.1 client calls a bidi RPC method, the caller has likely written application-level code that expects a full-duplex stream. Unless the server closes the TCP connection, the client code will often end up blocked because it's trying to read the response before it closes the request body.
> Close conn when HTTP/1.1 clients call bidi methods

- error.go
If your code already has an instance of `Any`, it's a pain (and not even guaranteed to be possible at runtime!) to unmarshal the message therein only to re-wrap it in order to put it in an `ErrorDetail`.
Similarly, if you can't unmarshal the contained type, it may be useful to access the `Any` envelope.
This adds two new APIs for just this.
> add API to make it easier to work with ErrorDetail if you have/want an Any

- connect_ext_test.go
- protocol_grpc.go
In #406, I was too cavalier about `net/http.ResponseWriter`'s API to
send HTTP trailers. Because we're not calling `WriteHeader` before
between predeclaring our trailers and actually setting the trailer
values, we end up sending the same data as both HTTP headers and
trailers.
> Send gRPC error metadata only as HTTP trailers

- connect_ext_test.go
- handler.go
If a handler returns `nil, nil`, we're going to panic during
serialization. However, those stacktraces don't include any frames from
the handler itself, so it's very difficult to determine what the problem
is. This PR panics explicitly a bit earlier, so that we can include the
procedure name in the error message.
Fixes #405.
> Improve panic message on invalid handler returns

- connect_ext_test.go
- handler.go
- option.go
- protocol.go
- protocol_connect.go
Currently, it's difficult for proxies, net/http middleware, and other
"in-between" code to distinguish unary Connect RPC requests from other HTTP
traffic (especially with JSON payloads, which use the common `application/json`
Content-Type). To work around this, any in-between code today must check
whether the HTTP path matches a known RPC method, which requires intimate
knowledge of the service schema. This isn't great.
To work around this limitation, we've added an optional header to the
specification for Connect RPC requests: `Connect-Protocol-Version`. Generated
clients always send this header, so the vast majority of traffic should include
it. Servers _may_ require that requests include this header, which helps
proxies and net/http middleware identify _every_ Connect request. This …
> Add support for Connect-Protocol-Version header

- connect_ext_test.go
- protocol_connect.go
- protocol_grpc.go
If the caller sets a User-Agent manually, we shouldn't clobber it. This
should unblock some internal use cases where people want to use
User-Agents to identify internal services, environments, etc.
> Don't clobber custom User-Agents

- client_stream.go
- connect.go
- handler_stream.go
On all applicable types and methods, explicitly document that headers
and trailers beginning with "Connect-" and "Grpc-" are reserved for use
by the RPC protocols.
This gets pretty repetitive. We could instead add a section to the
package-level docs, but my impression is that most people only read the
GoDoc for the methods/types they're interested in (so repeating
ourselves is more likely to work).
Relates to the discussion on #430.
> Document reserved headers more prominently

- error.go
- protocol_connect.go
- protocol_grpc.go
Currently, only the Connect runtime can create errors that return true
when tested by `IsWireError`. However, streaming RPCs commonly indicate
partial failure by including an error code and message in their response
message. To propagate these partial failures properly, clients need a
way to construct wire errors. This commit adds `NewWireError` to satisfy
this use case.
Fixes #420.
> Add NewWireError

- handler_ext_test.go
- protocol.go
- protocol_connect.go
- protocol_grpc.go
- protocol_test.go
The connect handler returns http.StatusUnsupportedMediaType when a request has a `Content-Type: application/json; charset=UTF-8` header. However, according to [RFC 9110 Section 8.3.2]( https://httpwg.org/specs/rfc9110.html#rfc.section.8.3.2), the charset parameter value should be treated as case-insensitive.
In this PR, I have modified the charset parameter value for user requests and acceptable content types of handlers to all be handled in lowercase.
> Match Content-Type charset case-insensitively

- connect.go
We've got two notable changes merged and unreleased: adding `NewWireError` and making our charset matching case-insensitive. The former change adds new APIs, so we should bump the minor version number.
> Prepare for v1.5.0

- protocol_connect.go
- protocol_grpc.go
The fmt.Sprintf stood out again in my profiling as a relatively hot path, and through the lifetime of an application, this value will not change. So we can generate this header value at init() time and avoid the extra memory allocation as well on each request.
> Minimize allocations writing User-Agent header

- protocol.go
- protocol_test.go
For context, this function is run on every request within ServeHTTP, and the mime parsing and now lowercasing, is a marginal, but non trivial amount of memory allocations.
The expensive bit is hitting the mime.FormatMediaType path, when we already have a canonical form.
This removes the most expensive part over arguable the most common cases where there are no additional parameters on the Content-Type.
```
$ go test -bench '^BenchmarkCanonicalizeContentType$' -run '^$' .
goos: darwin
goarch: arm64
pkg: github.com/bufbuild/connect-go
BenchmarkCanonicalizeContentType/simple-10         	92344741	        12.85 ns/op	       0 B/op	       0 allocs/op
BenchmarkCanonicalizeContentType/with_charset-10   	 1744219	       693.8 ns/op	     424 B/op	       6 allocs/op …
```
> Minimize allocations parsing Content-Type

- error_writer.go
- handler.go
- header.go
- protocol.go
- protocol_connect.go
- protocol_grpc.go
There are a lot of attempts to directly set header values already, this unifies all Get/Set/Add/Del accesses to assume a canonical form already.
In my personal testings, this actually stands out in our hot paths in flame graphs doing header Get/Sets. Within this codebase, we already have constants in place already in the correct formats.
I've dug so deeply into this in the past that I created https://github.com/mattrobenolt/go-httpheaders which specifically highlights benchmarks of direct access vs using the Get/Set helpers.
Since these are called multiple times in very hot paths, it's a worthwhile optimization since we can trust the inputs.
> Optimize header access

- connect.go
- protocol.go
- protocol_connect.go
- protocol_grpc.go
I don't know if there was an intention behind lazily initializing the Peer struct on-demand within the Peer() method, but from what I can tell, Peer() ends up being called 100% of the time in every path I've seen, and within NewClient, it's ultimately called twice.
Within NewClient, we also parse the params.URL then multiple times through url.ParseRequestURI then again through url.Parse, which is rather expensive and requires at least 1 heap allocation for the url.URL struct which we discard.
This behavior changes so the URL itself is parsed 1 time, then pass the url.URL struct to both functions that need it. As well as memoize the actual Peer on our concrete Client struct.
There is a slight change in behavior, but from my understanding, this seems safe:
validateRequestURL runs through …
> Optimize Peer lookups

- codec.go
- codec_test.go
Return a more understandable error when the JSON codec attempts to
unmarshal an empty body.
Fixes #452.
> More explicit error on empty JSON bodies

- protocol_grpc.go
- protocol_grpc_test.go
As a partial solution to #453, lower-case keys when appending gRPC-Web trailers to the response body. This is uncontroversial, since it only affects a portion of the wire format specific to gRPC-Web.
This does _not_ address trailers-only responses or standard response headers, which the gRPC-Web specification seems to also demand in lowercase.
> Use lowercase keys for gRPC-web trailers appended to the response body

- codec.go
When users try to use Connect with types generated by v1 of the protobuf
runtime (github.com/golang/protobuf), they get a generic message
complaining that their type doesn't implement `proto.Message`. This is
confusing, because the message does implement a `proto.Message`
interface - just from a different `proto` package. This PR adds a bit of
logic to the protobuf codecs to provide better errors in this case.
This error message is intentionally long: it uses
"github.com/golang/protobuf" and "google.golang.org/protobuf" rather
than "v1" and "v2" to avoid confusion with proto2 and proto3, and it
includes a link to a Go blog post that explains the migration in detail.
@cyriltovena ran into this, as did a few other other users I've spoken to.
Let's save them some debugging time :)
> Improve errors for outdated protobuf runtimes

- codec.go
- codec_test.go
Unfortunately, protobuf offers no story whatsoever for canonicalization of protobuf or protojson output. It seems the best we can get is to just make it deterministic within each implementation.
Question: I did not add tests for this particular code because codecs are currently not tested on their own. Should we start having unit tests for the codecs now?
Related issues:
* https://github.com/golang/protobuf/issues/1121
* https://github.com/golang/protobuf/issues/1373
> Add stable codec interface and implementations

- handler_stream_test.go
Clarify that the sole purpose of the test in `handler_stream_test.go` is to verify a safety property of the `ClientStream` iterator. A similar testing strategy isn't worthwhile for `ServerStream` or `BidiStream`, because they're not iterators.
> Clarify purpose of handler_stream_test.go

- client.go
- duplex_http_call.go
- protobuf_util.go
- protocol.go
- protocol_connect.go
- protocol_grpc.go
This stood out on flame graphs due ultimately to the http.NewRequestFromContext call, which ends up calling url.Parse and this happens on every single RPC call.
I did an optimization in #447 which similarly, and this is a natural extension of this.
We can just parse the url string once during NewClient, validate at that point, then tag along the parsed *url.URL everywhere else and never use it as a string again. This value never mutates through the lifetime of a Client and isn't publicly available on any structs.
Before:
After:
> Parse the url only once per Client

- Makefile
We're automatically fixing badly-formatted files in `make lintfix`; we
should check formatting in `make lint`.
> Check protobuf formatting in make lint

- client_ext_test.go
- connect.go
- protocol_connect.go
This was missing from the original server PR.
Q: Should we do anything for the accept header?
> Connect Get: Add serverside compression support

- connect.go
> StreamType constants should not be untyped numerics

- client.go
Neither `ServerStream` nor `ServerStreamForClient` include `Spec()` and `Peer()` methods. This is presumably because the signatures for handlers and stubs includes a `Request`, which _does_ have these methods.
However, on the client side, when invoking a server stream, these fields were never populated on the `Request`. They are technically still accessible via `stream.Conn()`. But since `ClientStream` and `BidiStream` have methods for these, without making the caller poke into the underlying conn, it seemed like this was likely not the expected way to retrieve these attributes.
So this PR simply updates the client-side stub so that calling a server-stream method _does_ populate the relevant fields of the `Request`. This provides convenient and consistent access to these fields for client …
> Client.CallServerStream should populate spec and peer of Request

- .golangci.yml
- client_ext_test.go
- error.go
- error_example_test.go
- error_not_modified_example_test.go
- protocol_connect.go
If servers want clients to cache responses to HTTP GETs, they'll also
need a mechanism to return HTTP 304s. Unfortunately, we can't introduce
a new status code without breaking our promise that clients can switch
protocols with just a configuration flag, so we need a sentinel error
instead.
> Add APIs to make and handle conditional GETs

- cmd/protoc-gen-connect-go/main.go
- connect.go
- internal/gen/connect/ping/v1/pingv1connect/ping.connect.go
Prepares for the Connect v1.7.0 release, featuring Connect Get support.
Changes the `IsAtLeastVersion1_6_0` constant to `IsAtLeastVersion1_7_0` too, since it actually is from changes that only landed afterwards.
> Prepare for v1.7.0

- error.go
- header.go
To match typical Go style (even for unexported identifiers), the first word of most documentation comments should be the identifier name.
> Prefix comments with correct identifier name

- connect.go
Following the example of `Code`, implement `fmt.Stringer` for `StreamType`. This makes it easier to use stream types in logs, traces, metric tags, and the like.
> Implement fmt.Stringer interface for StreamType

- Makefile
Fixes https://github.com/bufbuild/connect-go/issues/506.
> Fix Makefile quotes

- client_ext_test.go
- error_not_modified_example_test.go
- protocol.go
Fixes #502 to expose the HTTP method in handlers.
> Expose HTTP method in unary handlers

- duplex_http_call.go
If we fail to discard bytes, we should still close the response body.
> Always close response body in CloseRead

- connect.go
Prepares for the Connect v1.8.0 release, containing mostly bugfixes, but also adding an API to access the `HTTPMethod` of a request.
> Prepare for v1.8.0

- codec.go
- codec_test.go
The current JSON unmarshaling logic tightly couples clients and servers:
clients can't unmarshal messages containing new fields, and servers can't
unmarshal messages containing ancient fields that have since been deleted. This
is counter to the typical protobuf forward- and backward-compatibility story,
and is far more restrictive than the binary codec. This PR loosens the default
behavior to discard unknown fields.
Fixes #477.
> Discard unknown JSON fields by default

- .golangci.yml
- bench_test.go
- client_example_test.go
- client_ext_test.go
- cmd/protoc-gen-connect-go/main.go
- connect_ext_test.go
- error_example_test.go
- error_not_modified_example_test.go
- error_writer_example_test.go
- handler_example_test.go
- handler_ext_test.go
- interceptor_example_test.go
- interceptor_ext_test.go
- recover_ext_test.go
Add `connect` and `pkngv1` import aliases for packages whose name doesn't match.
similar https://github.com/bufbuild/knit-go/pull/22
> Lint for explicit import aliases

- connect_ext_test.go
- duplex_http_call.go
- handler.go
- protocol.go
- protocol_connect.go
Allows Host to set the request.Host on the client and promotes request.Host back to a Header in the handler.
Fixes #513
> Allow clients to set Host in headers

- handler.go
- protocol.go
Remove allocation of an array for each request by mapping the handlers by methods. Follows pattern of caching allow method and content types.
```
│  allocs/op  │  allocs/op   vs base           │
Connect/unary-8   247.0 ± ∞ ¹   243.0 ± ∞ ¹  ~ (p=1.000 n=1) ²
```
> Cache mapping of methods to protocol handlers

- protocol_connect.go
- protocol_connect_test.go
After testing many approaches, I think this is the most reasonable one. At least with Go JSON, there is no reasonable approach I could find that will give better performance or memory allocation characteristics to do this in one single pass. This approach should also have a _relatively_ small impact on trailers that are already canonicalized, since they will trivially fall into the `CanonicalMIMEHeaderKey` fast-path. The impact on the response path will probably be measured in hundreds of nanoseconds to microseconds in most cases, which is not ideal, but we definitely have bigger fish to fry, and correctness is important.
Closes #524.
> Canonicalize Connect Streaming Trailer names

- client_get_fallback_test.go
- option.go
Was this unexported on purpose? This seems like a very valuable option for anyone that wants to actually use HTTP GET requests. Also, it was fully specified as if it was exported, even though it was unexported and used by a single test case.
> Export max URL size option

- error_writer.go
- protocol_grpc.go
- protocol_grpc_test.go
Both `grpcPercentEncode` and `grpcPercentDecode` need to allocate a string and can use `strings.Builder` to own the allocation. Small optimization with `Grow` to give a hint to the size. 
```
goos: darwin
goarch: arm64
pkg: github.com/bufbuild/connect-go
│ current.txt  │                new.txt                │
│    sec/op    │    sec/op     vs base                 │
GRPCPercentEncoding-8   408.6n ± ∞ ¹   371.7n ± ∞ ¹        ~ (p=1.000 n=1) ²
GRPCPercentDecoding-8   79.59n ± ∞ ¹   65.24n ± ∞ ¹        ~ (p=1.000 n=1) ²
geomean                 180.3n         155.7n        -13.65%
¹ need >= 6 samples for confidence interval at level 0.95
² need >= 4 samples to detect a difference at alpha level 0.05
│ current.txt │               new.txt                │
│    B/op     │    B/op      vs base …
```
> Use strings.Builder for gRPC percent methods

- envelope.go
In some error handling cases, we're retrieving a value from the sync.Pool and explicitly not returning it. Instead, we might simplify things and just allocate a buffer (since we already know the size) and use it and not put extra work on the pool to garbage collect objects that are retrieved but never returned.
> Simplify code when pooled buffers aren't returned

- connect_ext_test.go
- envelope.go
- protocol_connect.go
On [Unmarshal](https://github.com/bufbuild/connect-go/blob/929c254ef86fbd5a131f0740fff25971fc65befa/envelope.go#L235-L239) we return `io.EOF` if there is no envelope header. The `errSpecialEnvelope` wraps `io.EOF` and is used in client code to check for [stream errors](https://github.com/bufbuild/connect-go/blob/929c254ef86fbd5a131f0740fff25971fc65befa/client_stream.go#L135-L137). To distinguish between them we can instead check on `Receive` streams if the error is not a known `errSpecialEnvelope`  and return an `io.ErrUnexpectedEOF`.
Fixes https://github.com/bufbuild/connect-go/issues/397
> Capture unexpected io.EOF errors as io.ErrUnexpectedEOF

- connect_ext_test.go
- envelope.go
- protocol_connect.go
- protocol_grpc.go
Cover the gRPC and gRPC-Web protocols in the tests for `io.ErrUnexpectedEOF`, and ensure that error codes and observable `errors.Is` behavior is consistent for all 3 supported RPC protocols.
> Surface io.EOF errors as io.ErrUnexpectedEOF for gRPC

- README.md
Update the buf studio URL to point to the new location.
Thanks to @johanbrandhorst for the tip.
> Update buf studio URL in README

- connect_ext_test.go
- duplex_http_call.go
- envelope.go
- protocol.go
- protocol_grpc.go
For connect and gRPC-web on receiving end of stream payloads ensure no extra data is written by draining the reader and erroring on more data.
Extension of https://github.com/bufbuild/connect-go/pull/533
Fixes https://github.com/bufbuild/connect-go/issues/427
> Drain stream and error on trailing data

- compression_test.go
- connect_ext_test.go
- error_writer.go
- handler.go
- interceptor_example_test.go
- option.go
Allows servers to set specific configuration based on the methods Spec.
This can be used to configure a specific route with different limits, such as:
```go
connect.WithConditionalHandlerOptions(func(spec connect.Spec) (options []connect.HandlerOption) {
if spec.Procedure == pingv1connect.PingServicePingProcedure {
options = append(options, connect.WithReadMaxBytes(1024))
}
return options
})
```
> Add WithConditionalHandlerOptions for conditional options

- README.md
Update the README to call the new demo service correctly.
> Update demo service calls

- protocol_connect.go
The `marshalAppender` interface was previously only used in the envelope writer. That means it was already reusing buffers from the pool for marshaling messages in all other protocols (Connect streaming, gRPC, and gRPC-Web); it was just missing from here.
The envelope writer logic is much more complicated, where it tries to use a copy to save the allocation of a `bytes.Buffer` struct to wrap the `[]byte`. I'm curious if that's been benchmarked and how big of a difference it really makes. I did not add the same logic here, but I can if we really think it's important. Do let me know!
I was also looking through the implementation of `bytes.Buffer.Write`, which under the does a `copy` between bytes slices. And in the case where marshalling did not have to increase the buffer capacity, the src …
> Reuse buffers when marshaling messages in unary Connect protocol

- .github/workflows/ci.yaml
- .github/workflows/windows.yaml
- .golangci.yml
- Makefile
- README.md
Include Go 1.21.0 in CI, and update `golangci-lint` to a version that supports
the new runtime.
As part of this change, we're committing to support for the last 3 versions of
Go. This ends up including a version of Go that no longer receives security
patches, but it matches AWS and some large companies' very slow upgrade cycles.
> Include Go 1.21.0 in CI

- Makefile
Now that Go 1.21 has `GOTOOLCHAIN`, we don't need this homegrown
mechanism anymore.
> Drop homegrown $GO Make support

- connect_ext_test.go
- protocol_grpc.go
The gRPC-Web pseudo-specification isn't totally clear, but it sounds
like it requires setting `X-User-Agent` instead of `User-Agent` as a
part of the protocol. This makes sense in browsers, where JS _can't_ set
`User-Agent`, but it's very odd for backend clients. This PR proposes
splitting the difference and setting both headers.
> Set X-User-Agent in gRPC-Web clients

- envelope.go
- handler_ext_test.go
For enveloped protocols (gRPC, gRPC-Web, and Connect streaming), this PR stops using the size from the envelope to preallocate buffers. This optimization rarely makes much difference in practice (because we're already pooling the buffers), and it's a potential abuse vector for malicious clients - they can trigger large allocations just by sending a 5-byte envelope.
> Eliminate preallocation for enveloped messages

- connect.go
Amend the version constant to go back to development. For merging after we tag
v1.11.1.
> Back to development

- Makefile
In `make lint`, we were running `buf format -d` twice. This PR removes
the more awkward invocation - I think it preceded the `--exit-code` flag.
> Remove extra protobuf formatting check

- README.md
This updates the link for the conformance repo (fka crosstests). This also changes the connect-web link to connect-es to accurately reflect that repo functionality.
Note - not intended to merge until the crosstest repo is moved.
> Update link for conformance repo

- MAINTAINERS.md
This PR proposes adding Matt Robenolt (@mattrobenolt), from PlanetScale, to the list of maintainers. Per [Connect's governance policy](https://connectrpc.com/docs/governance/project-governance), this also makes Matt one of the handful of maintainers with a vote on Connect RFCs.
Matt was one of Connect's earliest enthusiasts. He provided feedback on Connect's early releases, routinely helps other users in issues, and often reviews pull requests. He and his team also maintain a high-traffic Connect deployment, so his operational feedback has been incredibly valuable. Thanks for your contributions, Matt!
> Add Matt Robenolt to MAINTAINERS.md

- cmd/protoc-gen-connect-go/main.go
Use the protobuf runtime's `FullName` rather than our own, bug-prone implementation.
Fixes https://github.com/connectrpc/connect-go/issues/597.
> Use FullName for service route generation

- codec.go
- envelope.go
- protocol_connect.go
This is so that a custom `Codec` can choose what details to reveal to clients, in cases where emitting the destination message type is considered to leak too much information.
See #584 for more context.
> Move the indication of destination message type into Codec

- envelope.go
- envelope_test.go
I believe this fixes a bug where calling to `r.reader.Read` before all 5 bytes of the prefixes are ready causes an unnecessary `ErrUnexpectedEOF` (resulting in a client error `invalid_argument: protocol error: incomplete envelope: unexpected EOF`).
Switching to use `io.ReadFull` guarantees that the `envelopReader` will wait until the full prefixes is available before proceeding. Error handling should be identical to before due to the semantics of `io.ReadFull`. If fewer than 5 bytes are read and then `EOF` is hit, it will return `ErrUnexpectedEOF`. If any other error is hit, it will be returned as expected.
> Try to read full prefix in envelope reader

- .golangci.yml
We've disabled this linter in other projects, so let's stay as
consistent as we can.
> Disable nonamedreturn linter

- envelope.go
Tiny fix to generalized the error message.
> Remove gRPC error message from envelope error

- envelope.go
Three small fixes:
- [`io.ReadFull`](https://pkg.go.dev/io#ReadFull) on prefixes can't return an `io.EOF` if `prefixBytes > 0`
- Cast `size` to `int64` over `int` to avoid the overflow check
- `prefixBytesRead` must equal 5 on success
> Cast size as int64 to remove overflow checks

- Makefile
Add `--modules-download-mode=readonly` and `--timeout=3m0s` to running `golangci-lint`.
> Add flags to running golangci-lint

- internal/assert/assert.go
Internal assert package returns booleans for allowing conditional behaviour but currently can't be used as `t.Fatal` is called suspending execution. It's also not safe for `t.Fatal` to be called outside of the main go routine running the test. Use `t.Error` to report errors instead.
Example: https://github.com/connectrpc/connect-go/blob/2be1555cbf36879b6b1197cd09bc6e4cbe10290f/client_ext_test.go#L212 under failure would panic the client or server go routines not the test handlers.
> Report assert errors as t.Error

- client.go
- client_ext_test.go
- cmd/protoc-gen-connect-go/main.go
- connect.go
- handler.go
- internal/gen/connect/collide/v1/collidev1connect/collide.connect.go
- internal/gen/connect/import/v1/importv1connect/import.connect.go
- internal/gen/connect/ping/v1/pingv1connect/ping.connect.go
- option.go
New field Schema of type `any` on [`Spec`](https://github.com/connectrpc/connect-go/pull/629/files#diff-82f6a0eb10c47bc6590f594adc997b5a12de370dfd735a05c44cf8ff6fbf7a12R318). For proto based schemas the type will be of `protoreflect.MethodDescriptor`. This allows for easy introspection to interceptors.
Updated generated code to add the new `WithSchema` option to both handlers and clients. Schema is fetched from the proto file using the [`file.GoDescriptorIdent`](https://pkg.go.dev/google.golang.org/protobuf/compiler/protogen#File). To ensure generated code is matched with a library that includes the option a new version tag is added for v1.13.
For a unary request one can access the input and output descriptors by casting the interface and using protoreflect:
```go
methodDesc, ok := …
```
> Add Schema field to Spec for introspection

- connect_ext_test.go
- internal/memhttp/memhttp_test.go
Locally increasing the number of concurrent streams and running with `-race` generates:
```
writeRequest io.ErrClosedPipe
2023/11/03 10:19:46 timeout waiting for SETTINGS frames from pipe
writeRequest io.ErrClosedPipe
--- FAIL: TestConcurrentStreams (35.69s)
connect_ext_test.go:490: failed to send request: unknown: write envelope: EOF
connect_ext_test.go:490: failed to send request: unknown: write envelope: EOF
```
Large number of go routines can timeout past the arbitrary limit of 2 seconds in the HTTP2 libraries. See comment [here](https://github.com/golang/go/issues/60359#issuecomment-1560113923).
Bind the concurrency to [`runtime.GOMAXPROCS`](https://pkg.go.dev/runtime#GOMAXPROCS) to reduce resource requirements for testing on different machines.
See …
> Debug concurrent streams test

- connect_ext_test.go
- duplex_http_call.go
`TestStreamForServer` can fail on `Send(nil)` returning `io.EOF`. This occurs because `Send(nil)` will try to `Write(nil)` to the request body pipe. In almost all cases this will be read (and therefore succeed) when buffering the request body. However, on the server returning quickly, the request can be closed causing the `Send` to fail with `io.EOF` error. 
To ensure a `Send` succeeds we need to match it with a correlating `Receive` in the server. Nil writes will never be guaranteed unless the server tries to `Receive` a message, which would read the request body and therefore enforce the successful drain. This is a problem for `Send(nil)` as the intended behaviour is to ensure the request headers are sent, which does complete but returns with an unexpected error.
To solve for …
> Debug flaky `TestStreamForServer` test

- error.go
- error_test.go
- protocol_connect.go
The previous implementation _assumed_ that the `type_url` field in an `Any` would _always_ have a `type.googleapis.com/` prefix. Though that is typical in practice, it is not actually required per the spec for that field. In fact, `protoc` allows the use of `Any` messages (inside message literals for complex option values) that contain a prefix of `type.googleprod.com/` (therefore, so does the `buf` CLI).
The way all protobuf runtimes handle `Any` is to instead look at the last path element and ignore the prefix (which is also mentioned in the spec for the `type_url` field). So this makes the code more resilient to unexpected values for type URLs. Previously, the `ErrorDetail.Type()` method would return the full URL, instead of the type name, in the event that the URL had an unexpected …
> Type URLs can have any host and even include URI scheme

- client_ext_test.go
- handler.go
- handler_ext_test.go
- protocol.go
- protocol_connect.go
More stuff that @smaye81 found when developing conformance test cases, FTW!
The client should not include content headers ("content-type", "content-encoding", "content-length") since there is no body and everything is in the query string.
And the server should explicitly disallow a request body. It accepts content headers, but they are ignored and allowed as long as there is no body content.
> Improve GET request handling: clients should not include content headers, servers should disallow a body

- duplex_http_call.go
- envelope.go
- envelope_test.go
- error_writer.go
- protocol_connect.go
- protocol_connect_test.go
- protocol_grpc.go
- protocol_grpc_test.go
To enable client retries, the http calls now operates directly on message payloads instead of relying solely on `io.Writer`s. This refactor replaces write operations with send operations at message boundaries. It introduces a new interface, `messagePayload`, implemented by `*bytes.Reader`s and `*envelopes`, enabling them to adopt sender operations.
- A new interface, `messagePayload`, implemented by `*bytes.Reader` and `*envelope`, allowing for adoption of sender operations.
- A new interface, `messageSender`, implemented by `*duplexHTTPCall`, which acts on `messagePayloads` to send the message.
- An adapter `writeSender` for `http.ResponseWriter` to implement `messageSender` via converting send payloads to write operations. 
- Replaced write operations with send operations at message …
> Refactor http calls to support message payloads

- client_ext_test.go
Test case emits extremely noisy logs from TLS handshake errors due to closing many connection. Avoid logging server logs for this test case as they impact readability of others.
```
2023/12/11 15:57:19 http: TLS handshake error from 127.0.0.1:61647: read tcp 127.0.0.1:60080->127.0.0.1:61647: read: connection reset by peer
2023/12/11 15:57:19 http: TLS handshake error from 127.0.0.1:61683: EOF
...
```
> Silence TestClientDeadlineHandling server logs

- connect_ext_test.go
- error_writer.go
`ErrorWriter` will now correctly classifying connect GET requests if the connect protocol version header is present or the connect protocol version is set in the URL query parameters. To handle connect GET requests without the protocol version the ErrorWriter will write errors as connect unary errors if the protocol is unknown. This ensures the error is always written to the client. The connect unary error payload is always in JSON and therefore makes a nice human-readable format for the caller. Clients are still recommended to check `IsSupported` first to ensure the protocol will match the desired and to provide fallback to other error writers if desired.
Fix for #637 . Defaults to connect unary errors. To support other fallbacks use the `(*ErrorWriter).IsSupported()` check before …
> Fix ErrorWriter connect GET protocol classifier

- RELEASE.md
Adds a new markdown file RELEASE.md to document the release process. Includes the required updates to source code files and a walk through for drafting and publishing a release.
> Create RELEASE.md for release docs

- connect_ext_test.go
- duplex_http_call.go
- duplex_http_call_test.go
- envelope.go
- internal/memhttp/memhttptest/http.go
Internal changes to the HTTP client to remove some of the overhead required for streaming calls but unnecessary for non-streaming client requests. This PR changes both of the non-streaming client request types: unary and server streams. These types will now create the client request with the message payload upfront before calling `client.Do`. This removes the overhead of the `io.Pipe` to convert the body from a reader to a writer and the extra goroutine required to write to the pipe asynchronously. From this we get improved functionality for non-streaming requests by setting the `Content-Length` header and implementing `GetBody` function to enable retries.
The buffer reuse semantics are kept the same for both unary and stream requests. This allows for simple error handling with a …
> Implement unary HTTP calls with retry support

- duplex_http_call_test.go
Fixes the LICENSE header for new test file introduced in https://github.com/connectrpc/connect-go/pull/649 . Causing CI failure on main: https://github.com/connectrpc/connect-go/actions/runs/7616456681/job/20743252336
> Fix LICENSE header

- protocol_connect.go
Adds two missing conversions 409 and 415 from the spec: https://connectrpc.com/docs/protocol#http-to-error-code
> Fix HTTP Status to Code mapping

- protocol_grpc.go
Some gRPC servers in the wild appear to only accept requests when the Content-Type subtype codec name is empty, implying the default of "proto". For example Google Cloud API endpoints appear to require Content-Type to be exactly `application/grpc` and disallow the equivalent explicit form `application/grpc+proto`, rejecting requests using the latter form by responding with a 404 and `Content-Type: text/html`.
It's unclear if this is a load balancer (mis)configuration issue, or a lack of support for specifying a codec in the server implementation, but the end result is the same.
Seeing as the subtype qualifier is optional for gRPC, let's try to prefer the implicit form when it is equivalent to the selected codec.
Note that this change only impacts gRPC. Elsewhere we continue to prefer …
> Prefer an implicit codec when using the gRPC default

- protocol_grpc.go
I pulled this commit into the conformance repo to verify that this change is compatible with the official gRPC-Web JS client. In fact, I added some conformance test cases around it (https://github.com/connectrpc/conformance/pull/770) to verify that a gRPC-Web client will correctly accept both forms of "empty" response (for both unary and streams):
1) Headers, no response messages, trailers in the body
2) Trailers-only (where trailers are in HTTP headers)
The only issue with the gRPC-Web JS client was that it doesn't like it when in-body trailers contains a key more than once. It doesn't fail, but later values overwrite earlier ones instead of it merging all of the values. (I went ahead and filed a bug for it: https://github.com/grpc/grpc-web/issues/1399. It's trivial to fix, so I might …
> Only use trailers-only response in grpc-web when there are no custom headers

- connect_ext_test.go
- duplex_http_call.go
- error.go
- protocol_connect.go
- protocol_connect_test.go
- protocol_grpc.go
- protocol_grpc_test.go
@smaye81 found some more bugs with new conformance test cases.
The client is not verifying that the response has the correct content-type. So this change adds that verification.
Some tests, that had simple handlers that weren't setting a valid content-type, had to be updated. Sorry for the large diff stats, but it's not as bad as it looks. This PR adds three new table-driven tests that account for 75% of the lines of code.
> Client should verify response content-type

- protocol_connect.go
- protocol_grpc.go
This also formats the grpc version of the check so it is consistent with the other two.
Addresses comment in prior PR: https://github.com/connectrpc/connect-go/pull/679#discussion_r1483403176
> Reduce scope of `err` var in response content-type checks

- duplex_http_call.go
This is the only one I see left, and this is one is in the hot path for every request.
> Replace a Header.Get call with getHeaderCanonical

- protocol_connect.go
We can swap TrimPrefix for just a string slice here since we're already guarding behind HasPrefix. TrimPrefix internally runs HasPrefix again, so we can just skip the redundant work.
> Remove redundant work when validating unary Connect response

- connect_ext_test.go
- envelope.go
- protocol_grpc.go
Previously, connect-go would accept a trailers-only gRPC response (where the trailers are in the HTTP headers, signaled by the presence of a "grpc-status" key in the headers) and assume it was valid w/out further verification.
However, it should reject trailers-only responses that _also_ include response body data and/or HTTP trailers, after the HTTP headers as those are malformed responses.
This _would_ have been caught by a conformance test, as exactly this sort of test is in the queue. But I haven't written those tests yet and just happened to notice when I was looking into something else in the reference client (working on somewhat-related checks of the wire-level details for gRPC-Web responses).
> Verify that a trailers-only response is well-formed

- envelope.go
- protocol_connect.go
- protocol_grpc.go
I just happened to notice while I was trawling through the grpc-web implementation for other reasons. I thought it might help to skip the copy and actually release this buffer back to the pool.
Looking at benchmark output, it at least does no harm. And the reduction in allocations does show up as it consistently performs ~0.5% fewer for Connect streams and gRPC-web calls (both unary and stream). Strangely, this reduction in allocations doesn't show up for bidi streams in either Connect or gRPC-Web 🤔. The benchmark results in terms of latency and bytes allocated is basically a wash -- no discernible difference (though admittedly, these results have greater volatility from run-to-run than the number of allocations 🤷).
Anyhow, since it doesn't make any significant different, I'm fine if …
> Release buffer for end-stream messages back to the pool

- error.go
- protocol_connect.go
- protocol_connect_test.go
- protocol_grpc.go
This makes the output of a connect-go server look more like the examples in the docs. For example, [this section](https://connectrpc.com/docs/protocol/#error-end-stream) shows this example:
```json
{
"code": "unavailable",
"message": "overloaded: back off and retry",
"details": [
{
"type": "google.rpc.RetryInfo",
"value": "CgIIPA",
"debug": {"retryDelay": "30s"},
}
]
}
```
However, actual output from a connect-go server would instead have a "debug" entry that looked like this:
```json
{"@type": "type.googleapis.com/google.rpc.RetryInfo", "retryDelay": "30s"}
```
The type was redundantly stated as it was marshaling the `google.protobuf.Any` wrapper to JSON instead of the contained message.
This removes the discrepancy. Error output from a connect-go server will be a little more concise and …
> Drop @type from Connect error detail debug string

- .github/workflows/ci.yaml
- .github/workflows/windows.yaml
- go.mod
- go.sum
- header.go
- internal/conformance/go.mod
- protocol_grpc.go
This PR bumps the go version to 1.22 and the min version to go1.20. This was prompted by this CI failure: https://github.com/connectrpc/connect-go/actions/runs/7932731168/job/21659863630 which I believe is related to this issue: https://github.com/golang/go/issues/55846.
Also included is a removal of a workaround for 1.19 header handling introduced here: https://github.com/connectrpc/connect-go/pull/406
> Upgrade to go1.22 and min version go1.20

- connect_ext_test.go
- envelope.go
- header.go
- header_test.go
- protocol_connect.go
- protocol_connect_test.go
- protocol_grpc.go
- protocol_grpc_test.go
This largely undoes a recent change to do more validation of trailers-only responses (#685), which disallows a body or trailers in what appeared to be a trailers-only response. In that change, a trailers-only response was identified by the presence of a "grpc-status" key in the headers.
In this PR, a trailers-only response is instead defined by the lack of body and trailers (not the presence of a "grpc-status" header). This PR also tweaks some other error scenarios:
* If trailers (or an end-stream message) is completely missing from a response, it's considered an `internal` error. But if trailers are present, but the "grpc-status" key is missing, it's considered an issue determining the status, which is an `unknown` error.
* Similarly, if a response content-type doesn't appear to be the …
> Reconcile trailers-only and misc error behavior with grpc-go

- connect.go
Below is a draft of the release notes that will accompany this release.
----
Since the last release, we have been significantly increasing coverage of our [conformance suite](https://github.com/connectrpc/conformance). This has identified several inconsistencies with other Connect, gRPC, and gRPC-Web implementations. This release includes several fixes that will help align this implementation with others, behavior that can be verified by the conformance tests going forward. The fixes are backward-compatible with gRPC and Connect clients and servers. They fix some aspects of the wire representation and edge-case handling of spurious requests and responses, and they may affect users directly inspecting HTTP requests and responses.
* Add @emcfarlane as a maintainer in #680 🎉
* Add …
> Prepare for v1.15.0

- .golangci.yml
- codec_test.go
- error_writer.go
- error_writer_test.go
- option.go
- protocol_connect.go
This PR fixes ErrorWriter to correctly return unsupported protocol if the option `WithRequireConnectProtocolHeader` is set and the header or query value isn't include in the request. It will now correctly return unsupported to ensure fallback options can process the error.
Fixes #699
> Fix ErrorWriter IsSupportedCheck with required connect protocol option

- internal/conformance/known-failing.txt
- internal/conformance/runconformance.sh
- protocol_connect.go
The conformance tests, as of v1.0.0-rc3, currently require behavior that matches the current behavior of connect-go: if the error JSON body in a Connect unary response can be unmarshaled but is missing the code, it defaults to using "unknown" as the code.
However, in the Connect unary format (and not any of the others), we also have a non-200 HTTP status that could be used to determine a potentially better default than "unknown". So this PR changes it so that connect-go uses the HTTP status in this case, instead of always using "unknown". (Also see https://github.com/connectrpc/conformance/issues/810.)
It _also_ updates the JSON unmarshaling of the error body so it accepts a `"code"` property with an invalid value. In this case, the invalid value is discarded, and due to the change …
> In connect unary protocol, fallback to code based on HTTP status if unable to deserialize it

- connect_ext_test.go
- handler_ext_test.go
- internal/conformance/known-failing.txt
- protocol.go
- protocol_connect.go
- protocol_connect_test.go
- protocol_grpc.go
This reconciles the implementation in this repo with the recent adjustments to HTTP<->Connect code mappings (https://github.com/connectrpc/connectrpc.com/pull/130).
The gRPC and Connect mappings from HTTP code to RPC code are now aligned, so I've unified them into a single function.
> Revise code mappings per latest changes to spec

- connect_ext_test.go
- error_writer.go
- error_writer_test.go
- handler.go
This PR changes the ErrorWriter to be more lenient with classifying protocols. Errors codecs are agnostic to the codec used. Therefore we avoid checking the codec in classifying the request. IsSupported will return true for an unknown codec which allows the server to encode a better error message to the client. If not supported a 415 error response could be used to match gRPC server like handling. If not supported and trying to write an error the ErrorWriter will default to connects unary encoding (consistent with current behaviour).
Fixes #689
> Fix ErrorWriter to be codec agnostic

- duplex_http_call.go
This is effectively a continuation of #659, catching two more places that needed to be instrumented.
This issue was discovered when running conformance tests (https://github.com/connectrpc/conformance/issues/813). It was occurring consistently with full-duplex streams against one particular server implementation. I think that implementation was eagerly doing a server-side cancelation of the stream when the server saw that its deadline had elapsed, and that other implementations generally don't do this. In this particular case, the framework was observing the "RSTStream" frame and returning a "canceled" code even though the operation's context had already elapsed and had a "deadline exceeded" error. So the RPC was returning a "canceled" error code when it ideally would instead return a …
> Update a couple of more places where we should return a context error if there is one

- connect.go
- connect_ext_test.go
- handler.go
- internal/conformance/known-failing.txt
The table in the [docs for gRPC status codes](https://grpc.github.io/grpc/core/md_doc_statuscodes.html) indicates that a "cardinality violation" -- when a stream is expected to have exactly one message and instead has zero or multiple -- should result in an "unimplemented" error code, both from clients upon observing a malformed response stream and from servers upon observing a malformed request stream.
This library was previously using "unknown" as the error code, fashioned after grpc-go, which apparently does not correctly implement this. Further, this library only validated the response stream, in the client. With this change, it uses the correct code and also validates the request stream, in the server.
> Use "unimplemented" code for cardinality violations

- connect_ext_test.go
- error.go
- error_writer.go
- header.go
- protocol.go
- protocol_connect.go
- protocol_grpc.go
This PR addresses issues when propagating errors from a client back to a handler. On the client side connect errors will contain all response headers: transport (`Content-Type`, `Content-Length`, etc), protocol and application headers. These could break the transport when trying to re-encode the error or leak sensitive information between services. For any wire errors (errors decoded from a client response) we now disable meta propagation. For other errors we now also restrict the headers propagated.
> Restrict metadata headers in error propagation

- connect_ext_test.go
- protocol_grpc.go
Currently, in the gRPC protocol, Connect will always serialize a `Status` proto and return it in the `Grpc-Status-Details-Bin` header. This differs from the [grpc-go](https://github.com/grpc/grpc-go/blob/master/internal/transport/handler_server.go#L247-L256) behavior, which is to only emit that header if the `Status` has a non-empty `Details` list. The remaining properties of `Status` (`message` and `code`) are still returned via dedicated headers, so returning the encoded `Status` message is redundant.
This PR aligns Connect's gRPC protocol with the `grpc-go` behavior, which also reduces the wire size of error responses in the common case that no details are provided. I chose not to match their behavior of `panic`ing when marshalling fails 😉 .
> Only send a serialized Status in the gRPC protocol if it has details

- connect.go
Below are draft release notes for this release.
----
This release is mostly bug fixes but also reconciles connect-go with recent updates to the specification regarding mapping of RPC error codes to/from HTTP status codes (see [connectrpc RFC 003](https://github.com/connectrpc/connectrpc.com/pull/148))
* Revise RPC error code <-> HTTP status code mappings per latest changes to spec by @jhump in #706
* Only send a grpc-status-details-bin trailer in the gRPC protocol if the error has details by @bhollis in #713
* Fix `ErrorWriter IsSupported` check to report false on ambiguous content-type and options indicate connect protocol version header is required by @emcfarlane in #700
* In Connect unary protocol, fallback to code based on HTTP status if unable to deserialize code from JSON body by …
> Prepare for v1.16.0

- internal/conformance/go.mod
- internal/conformance/go.sum
Not much different from rc4. But just to keep this repo pinned to latest release of the conformance tests.
> Update to latest conformance suite: v1.0.1

- connect.go
- protocol_connect.go
On error a connect unary handler will call `Close(err)` to send the final error. For non-nil errors this will always attempt to encode the header status by calling `WriteHeader`. If the body has already been written this triggers the following log via `http.Server`:
```
http: superfluous response.WriteHeader call from connectrpc.com/connect.(*connectUnaryHandlerConn).Close (protocol_connect.go:743)
```
The common case for this superfluous log is when a message send is interrupted, due to a context cancel or other write error, and the error is then attempting to re-encode the headers and body.
This PR now moves the `wroteBody` check to a `wroteHeader` check on the unmarshaller. When any payload is sent, including a nil field for header only, we now stop attempting to encode any following …
> Fix multiple header writes for connect unary on error

- connect.go
Draft release notes below.
----
This release contains a single bugfix.
* Fix redundant attempts to write headers in certain error cases in Connect unary RPCs by @emcfarlane in #726
**Full Changelog**: https://github.com/connectrpc/connect-go/compare/v1.16.0...v1.16.1
> Prepare for v1.16.1

- connect.go
There have been no real changes other than the dependency update of golang.org/x/net, to address 
[CVE-2023-45288](https://nvd.nist.gov/vuln/detail/CVE-2023-45288). So this will just be a tiny patch release.
Draft release notes:
----
This is a patch release to make sure that consuming modules won't be vulnerable to [CVE-2023-45288](https://nvd.nist.gov/vuln/detail/CVE-2023-45288).
* Update the golang.org/x/net dependency to v0.23.0 in #729.
**Full Changelog**: https://github.com/connectrpc/connect-go/compare/v1.16.1...v1.16.2
> Prepare for v1.16.2

- .golangci.yml
- connect_ext_test.go
- error_writer.go
- handler.go
- header.go
- protocol_connect.go
- protocol_grpc.go
This PR fixes the setting of protocol headers to avoid multiple value headers when providing metadata to a handler. The metadata headers are further restricted to avoid setting protocol headers like "Content-Type". This restriction allows the user to pass the response of a proxy call to a handler without having to filter the response headers themselves. This enforces the protocol headers are set by the handler and that they are unaffected from any user provided metadata.
Previously, returning the response of a client request to a handler would merge the headers together leading to protocol errors from invalid headers such as "Content-Type" having multiple values.
> Restrict handler metadata headers

- .golangci.yml
- Makefile
- client_stream_test.go
- connect_ext_test.go
- duplex_http_call.go
- error_test.go
- handler.go
- header.go
- protocol_connect.go
- protocol_grpc.go
Upgrades the linter version to the latest fixing small issues. For readability `nolint` global directives have been brought inline to avoid misuse. This fixes the issue brought up in #748. As a small cleanup the buf version has been brought to the latest.
> Chore upgrade linter

- Makefile
- go.sum
Run 'go mod tidy' as part of 'make generate'. This will ensure that it is run prior to passing CI as any modifications it makes will cause 'make checkgenerate' to fail.
> Run go mod tidy as part of generate

- .github/workflows/ci.yaml
- .golangci.yml
- Makefile
- go.mod
- option.go
Now that go 1.23 is out, we can update this repo to no longer support go 1.20.
> Require go 1.21, test with go 1.23

- duplex_http_call.go
- protocol_connect.go
The error message had a copy+pasta bug where it was showing the wrong prefix. This resulted in possibly very confusing error message where it complained that the content-type was wrong, but then said it was expecting exactly what it actually got.
> Fix error message about content-types

- connect.go
Below are draft release notes for this release. I decided to make it a minor version instead of a point release because:
* Supporting editions source files (#754) could be seen as an enhancement (even though it makes no real changes to the code and doesn't add any features or new API -- it just toggles something in the code gen response to allow it).
* Updating to require Go 1.21 (#770) seems like something worthy of a minor version instead of a point release.
----
* Enable `protoc-gen-connect-go` usage with Protobuf source files that use Editions by @jchadwick-buf in #754
* Prevent incorrect propagation of protocol-specific metadata by @emcfarlane in #748
* Fix error message about unexpected content-type by @jhump in #775
* Calls should return "unavailable" instead of "unimplemented" or …
> Prepare for v1.17.0 release

- connect.go
This PR is fix typo of comment in `connect.go`.
> FIX Typo Of Comment Out

- compression.go
Small optimization to avoid allocating a new reader when recycling compressors by using `http.NoBody`.
> Remove reader allocation for compressors pools

- client_stream.go
- duplex_http_call.go
This updates the behavior of the streaming client methods `BidiStreamForClient.CloseResponse` and `ServerStreamForClient.Close` to be non-blocking, aligning it with the standard behavior of `net/http`'s `Request.Body` closure.
Previously, the implementation used a graceful, blocking closure that fully read from the stream before closing. This allows for reuse of the underlying TCP connection. However, this behavior could lead to unexpected client hangs, as users may not anticipate blocking on close.
To address this, the closers no longer drain the stream. Documentation has been updated to clarify the behavior and provide users a workaround to keep the optimization by calling receive until the stream is drained. This avoids unexpected blocking behavior in client applications.
Fixes #789
> Make stream client closers non-blocking

- cmd/protoc-gen-connect-go/main.go
- cmd/protoc-gen-connect-go/main_test.go
This is the alternative option `package_suffix` re: https://github.com/connectrpc/connect-go/pull/803#pullrequestreview-2512877564. I'm not sure which one I like more - I don't like the name `same_package` that much, and this gives more flexibility, but I don't know if we want to offer that flexibility. Looking for opinions.
Regardless of if we choose this or #803 as-is, we should make sure the README.md documents the option.
> Add package_suffix option

- .github/workflows/windows.yaml
- Makefile
- internal/conformance/go.mod
We just missed this when we updated to Go 1.21. It was passing anyway because releases prior to 1.21 are lenient -- in that they will try to build and run code even if the `go` directive in `go.mod` indicates a newer version. And since none of the code was actually relying on new APIs, features, or semantics in Go 1.21, the tests would pass.
This also commits a change that `go mod tidy` keeps wanting to make to `internal/conformance/go.mod`. Our "checkgenerate" make target was previously catching these only in the main module. This PR includes a small change to `Makefile` so that this kind of thing can be caught in the conformance module, too.
> We don't support 1.20 anymore, so stop testing with it in Windows

- cmd/protoc-gen-connect-go/main.go
Change `opts` to `opt` in documentation for buf v2 schema.
Fix https://github.com/connectrpc/connect-go/issues/815
> Fix typo in Go docs for example buf configuration

- .github/workflows/ci.yaml
- .github/workflows/windows.yaml
- .golangci.yml
- Makefile
- buf.yaml
- client_ext_test.go
- code.go
- codec_test.go
- connect_ext_test.go
- duplex_http_call_test.go
- envelope.go
- envelope_test.go
- error_test.go
- go.mod
- handler_ext_test.go
- internal/memhttp/memhttp_test.go
- protocol_connect_test.go
- protocol_grpc.go
- protocol_grpc_test.go
- protocol_test.go
This upgrades the min Go support to v1.22 and the tools buf and golangci-lint, fixing any found lint issues.
> Upgrade min Go v1.22 and tooling

- .github/workflows/ci.yaml
- .github/workflows/windows.yaml
- README.md
- go.mod
- internal/conformance/go.mod
This changes the support posture for Go runtimes to mirror the Go SDK itself and to also mirror [recent changes](https://github.com/googleapis/google-cloud-go/commit/8a68e456d089e946bec93ffad6edb35eb0d29f93#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R23-R28) in the Google Cloud APIs for Go (starting January 1st, 2025).
The AWS APIs for Go still maintain support for three versions of Go, but they do have [a caveat](https://github.com/aws/aws-sdk-go-v2?tab=readme-ov-file#go-version-support-policy):
> **AWS reserves the right to drop support for unsupported Go versions earlier to address critical security issues.**
This caveat is topical because the reason I'm proposing changing to supporting only two versions is spurred by a security fix: [v0.36.0 of …
> Support latest two versions of Go instead of latest three

- client_ext_test.go
- codec_test.go
- connect_ext_test.go
- duplex_http_call.go
- header.go
- internal/memhttp/listener.go
- protocol_grpc_test.go
This is the result of running:
```
$ go run golang.org/x/tools/gopls/internal/analysis/modernize/cmd/modernize@latest -fix -test ./...
$ gofumpt -w .
````
Basically no substantial change except one update to use `maps.Copy`.
I'd personally recommend this as a nice habit to get into when we bump the minimum versions. I've found this picking up some good changes. It has even auto converted some calls like `strings.Split` into `strings.SplitSeq` in some of my codebases when applicable.
> Codemod to update syntax

- bench_test.go
- client.go
- client_ext_test.go
- client_stream.go
- cmd/protoc-gen-connect-go/internal/testdata/simple/gen/genconnect/simple.connect.go
- cmd/protoc-gen-connect-go/main.go
- connect.go
- connect_ext_test.go
- context.go
- error_example_test.go
- error_not_modified_example_test.go
- example_init_test.go
- handler.go
- handler_example_test.go
- handler_ext_test.go
- interceptor.go
- interceptor_ext_test.go
- internal/gen/simple/connect/collide/v1/collidev1connect/collide.connect.go
- internal/gen/simple/connect/ping/v1/pingv1connect/ping.connect.go
This adds the usage of CallInfo in context for issuing requests with the new simple API. This builds on top of the https://github.com/connectrpc/connect-go/pull/851 which implements the simple flag for unary and server-streaming
In addition, it adds integration tests for the simple and generics API.
> Implement CallInfo usage in context and add integration tests

- README.md
Reverting to the current README so that we don't advertise the simple flag until the release is complete.
> Revert README temporarily

- client.go
- client_stream.go
- context.go
- handler.go
This adds better comments to some of the new types by expanding on what is meant by each `Simple` type instead of using a generic description of 'simple mode'.
This also renames `streamCallInfo` to `streamingHandlerCallInfo` to better reflect its usage.
> Add better comments

- connect.go
- error.go
- error_test.go
- protocol_connect.go
- protocol_grpc.go
This is in relation to https://github.com/connectrpc/connect-go/pull/851. This standardizes on using `For` instead of `From` for all of our functions. The two words are interchangeable, and all of our public methods use `For`, so this has all of our private methods do so as well. A new public method `CallInfoFromHandler` is/was being introduced in #851, and in relation to renaming it to `CallInfoForHandler`, this furthers the standardization.
> Standardize on For over From

- .github/workflows/ci.yaml
- .github/workflows/windows.yaml
- README.md
- bench_test.go
- client_ext_test.go
- client_get_fallback_test.go
- cmd/protoc-gen-connect-go/main_test.go
- code.go
- compression_test.go
- connect_ext_test.go
- duplex_http_call_test.go
- envelope_test.go
- go.mod
- handler_example_test.go
- handler_ext_test.go
- interceptor_ext_test.go
- internal/conformance/go.mod
- internal/memhttp/memhttp_test.go
- protocol_connect_test.go
- protocol_grpc_test.go
- protocol_test.go
- recover_ext_test.go
Go v1.24 introduced H2C support in the standard library (fixing issues like graceful shutdown, [golang/go#26682](https://redirect.github.com/golang/go/issues/26682)), this documents its usage and bumps the minimum required Go version
> The server and client may be configured to support unencrypted HTTP/2 connections.
> Unencrypted HTTP/2 support uses “HTTP/2 with Prior Knowledge” (RFC 9113, section 3.3). The deprecated “Upgrade: h2c” header is not supported.
https://tip.golang.org/doc/go1.24#nethttppkgnethttp
I will do a separate PR to drop the experimental H2C module from the test suite, I have the changes ready.
> Bump minimum Go version to v1.24 and document H2C with stdlib

- connect.go
Below are the draft release notes for v1.19.1.
* Fix bounds check on envelope for 32-bit archs by @emcfarlane in #887
* Fix CallInfo header/trailer propagation on error responses by @emcfarlane in #892
**Full Changelog**: https://github.com/connectrpc/connect-go/compare/v1.19.0...v1.19.1
> Prepare for v1.19.1
